export const restList = [
  {
    data: {
      id: "549580",
      resName: "Fresh Meal's",
      avgRating: "4.3",
      cuisines: ["North Indian", "South Indian"],
      costForTwo: "₹300 for two",
      veg: true,
      isOpen: true,
      cloudinaryImageId: "v5e3atn9tmtgcca1onnr",
    },
  },
  {
    data: {
      id: "830418",
      resName: "Indian Coffee House",
      cloudinaryImageId: "2469fa88ee9b0b5d1366ba88f2a7fa7f",
      avgRating: "4.5",
      cuisines: [
        "South Indian",
        "North Indian",
        "Chinese",
        "Fast Food",
        "Beverages",
      ],
      costForTwo: "₹400 for two",
      veg: false,
      isOpen: true,
    },
  },
  {
    data: {
      id: "870899",
      resName: "Paras Mishthan",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/15/9de3a721-5e96-41d2-bb3e-3cbeff47fbd3_870899.jpg",
      avgRating: "4.3",
      cuisines: ["Beverages", "Sweets", "Snacks"],
      costForTwo: "₹150 for two",
      veg: true,
      isOpen: true,
    },
  },
  {
    data: {
      id: "672945",
      resName: "Annu's Kitchen's Queen Of Paratha",
      cloudinaryImageId: "dd519572ed1bed19de47e94186e743ea",
      avgRating: 4.5,
      cuisines: [
        "North Indian",
        "South Indian",
        "Chinese",
        "Beverages",
        "Fast Food",
        "Desserts",
      ],
      costForTwo: "₹200 for two",
      veg: true,
      isOpen: true,
    },
  },
  {
    data: {
      id: "658210",
      resName: "The Fusion Lounge",
      cloudinaryImageId: "fa4944f0cfdcbca2bec1f3ab8e3db3f7",

      avgRating: "4.1",
      cuisines: [
        "North Indian",
        "South Indian",
        "Chinese",
        "Beverages",
        "Fast Food",
        "Desserts",
      ],
      costForTwo: "₹300 for two",
      veg: true,
      isOpen: true,
    },
  },
  {
    data: {
      id: "255655",
      resName: "Cake & Cream",
      cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "pastery", "Cake", "Thick- shake"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
    },
  },
  {
    data: {
      id: "350363",
      resName: "Haldiram's Sweets and Namkeen",
      cloudinaryImageId: "25c3a7d394d6c5556b134385f7d665b0",
      avgRating: 4.6,
      veg: true,
      cuisines: [
        "North Indian",
        "South Indian",
        "Chinese",
        "Pizzas",
        "Fast Food",
      ],
      parentId: "391465",
      avgRatingString: "4.6",
      totalRatingsString: "100+",
    },
  },
  {
    data: {
      id: "154891",
      resName: "Rasraj Restaurant",
      cloudinaryImageId: "egbr63ulc8h1zgliivd8",
      locality: "Civil Line",
      areaName: "Civil Lines",
      costForTwo: "₹250 for two",
      cuisines: [
        "North Indian",
        "South Indian",
        "Street Food",
        "Chinese",
        "Pizzas",
        "Fast Food",
      ],
      avgRating: 4.2,
    },
  },
  {
    data: {
      id: "745961",
      resName: "Balaji Restaurant",
      cloudinaryImageId: "b8672fe52944c3599ea324d99d608300",
      locality: "Sai Rubber Stamp",
      areaName: "Jairaj Nagar",
      costForTwo: "₹149 for two",
      cuisines: ["South Indian", "North Indian"],
      avgRating: 4.8,
      veg: true,
    },
  },
  {
    data: {
      id: "798745",
      resName: "Friends Restaurant",
      cloudinaryImageId: "b14cd9fc40129fcfb97aa7e621719d07",
      locality: "Gayatri Nagar",
      areaName: "Jairaj Nagar",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Biryani", "Tandoor", "Kebabs"],
      avgRating: 4.2,
      parentId: "84308",
    },
  },
  {
    data: {
      id: "314737",
      resName: "RASOI the KITCHEN",
      cloudinaryImageId: "yjymo9nhyn7rhvafsrd3",
      locality: "Sriram Chowk",
      areaName: "Bazar Ward",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Maharashtrian", "Chinese", "Thalis"],
      avgRating: 3.9,
      parentId: "167341",
    },
  },
  {
    data: {
      id: "201454",
      resName: "Morsels restaurants",
      cloudinaryImageId: "aafe71251ef5328784652dc838cd91f3",
      locality: "Bazar Ward",
      areaName: "Chandrapur Locality",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "South Indian"],
      avgRating: 3.2,
      veg: true,
      parentId: "139266",
      avgRatingString: "4.2",
    },
  },
  {
    data: {
      id: "266124",
      resName: "Trimurti Restaurant",
      cloudinaryImageId: "8135c0066b06e2925c66930be4e9ffb5",
      locality: "Bazar Ward",
      areaName: "Chandrapur Locality",
      costForTwo: "₹150 for two",
      cuisines: ["Desserts"],
      avgRating: 3.9,
      veg: true,
      parentId: "217751",
      avgRatingString: "4.4",
    },
  },
  {
    data: {
      id: "509254",
      resName: "Saha Restaurant",
      cloudinaryImageId: "z1ez4uc9idul2uj2v87g",
      areaName: "Jairaj Nagar",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Biryani", "Thalis", "Beverages"],
      avgRating: 3.7,
      parentId: "174585",
      avgRatingString: "3.7",
    },
  },
];
